- name: Update admin regarding failure
  delegate_to: 127.0.0.1
  become: False
  slack:
    token: "{{ admin_token }}"
    msg: "Automation Failed, check logs and debug | {{ ansible_failed_result.msg }}"
    color: "danger"

- name: Debug message
  debug:
    msg: "Automation Failed, check logs and debug | {{ ansible_failed_result.msg }}"

- name: Stop the Automation
  delegate_to: 127.0.0.1
  fail:
    msg: "Terminating automation"